## ADDIDAS ANALISIS

In [2]:
!wget https://github.com/prayagpadwal/Adidas-Sales-Analysis/raw/main/Adidas%20US%20Sales%20Datasets.xlsx

--2025-09-15 23:37:06--  https://github.com/prayagpadwal/Adidas-Sales-Analysis/raw/main/Adidas%20US%20Sales%20Datasets.xlsx
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/prayagpadwal/Adidas-Sales-Analysis/main/Adidas%20US%20Sales%20Datasets.xlsx [following]
--2025-09-15 23:37:07--  https://raw.githubusercontent.com/prayagpadwal/Adidas-Sales-Analysis/main/Adidas%20US%20Sales%20Datasets.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 693038 (677K) [application/octet-stream]
Saving to: ‘Adidas US Sales Datasets.xlsx’

Adidas US Sales Dat 100%[===================>] 676.79K  --.-KB/s    in 0.05s

2025-09-15 23:37:07 (12.8 MB/s) - ‘Adidas US Sales Datasets.xlsx’ saved [693038/693038]

In [3]:
import pandas as pd
data = pd.read_excel("Adidas US Sales Datasets.xlsx")

In [4]:
data.head(3)

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.0,0.50,In-store
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.0,0.30,In-store
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.0,0.35,In-store

0. Cuantas filas y columnas tiene la tabla?

In [ ]:
data.shape

(9648, 13)

0.1 Cual es la unidad de observación de la tabla?

1. Cuales fueron las ventas totales?

In [ ]:
data["Total Sales"].sum()

np.float64(899902125.0)

1.1 Cuanto fue la ganancia operacional total?

In [ ]:
data["Operating Profit"].sum()

np.float64(332134761.45000005)

1.2 Cuanto fue el margen promedio total ?

In [ ]:
data["Operating Margin"].mean()

np.float64(0.42299129353233833)

1.3 Por que el margen promedio y no el total. Explique con palabras

2. Cuales fueron las ventas totales por Retailer?

In [ ]:
A= data.groupby("Retailer")["Total Sales"].sum()

2.1 Cual fue la ganancia operacional total por retailer?

In [ ]:
B= data.groupby("Retailer")["Operating Profit"].sum()

2.3 Tomando los dos resultados de arriba: El ganancia operacional total y las ventas totales divida ambos resultados. Le tiene que dar el margen total de cada Retailer.

In [ ]:
A/B

Retailer
Amazon           2.696147
Foot Locker      2.726572
Kohl's           2.774009
Sports Direct    2.454779
Walmart          2.891873
West Gear        2.836120
dtype: float64

2.4 Cual fue el margen operacional promedio por retailer?

In [ ]:
data.groupby("Retailer")["Operating Margin"].mean()

Retailer
Amazon           0.417871
Foot Locker      0.417933
Kohl's           0.419291
Sports Direct    0.444892
Walmart          0.406534
West Gear        0.417856
Name: Operating Margin, dtype: float64

2.5 Por que los dos resultados anteriores le dieron diferente? Argumente

En el 2.3 se calcula el margen total de cada retailer, suma todas sus ventas y ganancias y luego hace la división. En el 2.4, en diferente, primero se obtiene el margen promedio, ya que se calcula el margen de cada transacción por separado y después se promedian los resultados.

3.1 Retailer que mas unidades totales vende? Saque cuanto vende en unidades cada retailer y busque el mayor

In [ ]:
data["Retailer"].max()

3.2 Cual fue el producto que mas unidades totales vendió?

In [ ]:
data["Product"].max()

3.3 Cual es el metodo de venta que mas ventas totales tuvo y más ventas promedio

In [ ]:
data.groupby("Sales Method")["Total Sales"].mean()

3.4 Cual Fue el estado que más ventas totales tuvo ?

In [5]:
data["State"].max()

'Wyoming'

4. Teniendo en cuenta los resultados de arriba: 1. Tome el Retailer que vendio
mas 2. El estado que vendio mas 3.el producto que vendio mas y el metodo de ventas que vendio más 4. Filtre y genere un dataframe con ellos 5. llamelo como un nuevo dataframe

In [ ]:
data_filtered = data[
    (data['Retailer'] == data["Retailer"].max()) &
    (data['State'] == data["State"].max()) &
    (data['Product'] == data["Product"].max()) &
    (data['Sales Method'] == data["Sales Method"].max())
]
display(data_filtered)

Empty DataFrame
Columns: [Retailer, Retailer ID, Invoice Date, Region, State, City, Product, Price per Unit, Units Sold, Total Sales, Operating Profit, Operating Margin, Sales Method]
Index: []